"""Bundle builder — write the canonical dated bundle per BUNDLE_CONTRACT.md.

Writes `<repo>/<bundle.root>/<date>/` with the engine-owned file set:
  meeting.yaml   — machine-readable parse anchor (provenance incl. repo HEAD)
  PREP.md        — in-the-room script (Ask PI: 🔴 workstream asks first, then D.N)
  synthesis.md   — full reconciliation
  artifacts/     — symlinks (never copies) to the regenerated deck + PDFs

Idempotent: re-running for the same date regenerates ONLY the engine-owned files
and leaves human/LabSync files (TRANSCRIPT.md, feedback-extracted.md, …)
untouched. Additive: a build writes a new dated dir; it never edits another dir.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from . import __version__
from .aggregate import WorkLedger, aggregate
from .deck import DeckResult, build_deck, symlink_into
from .manifest import Project
from .synthesize import rank_commits_for_headline, synthesize

# Reserved names the engine NEVER writes (human- or LabSync-owned).
RESERVED_NAMES = {
    "TRANSCRIPT.md", "feedback-extracted.md", "action-items.md",
    "writeback-log.md",
}


@dataclass
class BuildResult:
    bundle_dir: Path
    meeting_yaml: Path
    prep: Path
    synthesis: Path
    deck: DeckResult
    artifacts: list
    ledger: WorkLedger


def build(
    project: Project,
    date: str,
    *,
    since: str,
    until: str | None = None,
    kind: str = "pi-meeting",
    build_deck_flag: bool = True,
    version: str = __version__,
) -> BuildResult:
    until = until or date
    bdir = project.bundle_dir(date)
    bdir.mkdir(parents=True, exist_ok=True)

    ledger = aggregate(project, since, until)

    # --- synthesis.md ---
    synthesis_text = synthesize(project, ledger, version=version)
    synth_path = bdir / "synthesis.md"
    synth_path.write_text(synthesis_text, encoding="utf-8")

    # --- deck (trigger the project's builder) + artifacts/ symlinks ---
    deck_result = build_deck(project, dry_run=not build_deck_flag)
    artifacts: list = []
    seen_targets: set = set()

    def _link(target: Path) -> None:
        if target.exists() and str(target) not in seen_targets:
            seen_targets.add(str(target))
            artifacts.append(symlink_into(bdir, target))

    # the regenerated (or pre-existing) deck output, even if the build degraded
    deck_out = None
    if project.deck.get("output"):
        deck_out = project.repo / project.deck["output"]
    if deck_out is not None:
        _link(deck_out)
    # manuscript / SI PDFs surfaced by the evidence-glob mtime scan
    for ev in ledger.evidence_files:
        if ev["path"].endswith(".pdf"):
            _link(project.repo / ev["path"])

    # --- PREP.md ---
    prep_md = _render_prep(project, ledger, deck_result, artifacts, date, synth_path)
    prep_path = bdir / "PREP.md"
    prep_path.write_text(prep_md, encoding="utf-8")

    # --- meeting.yaml (the parse anchor) ---
    meeting_yaml = bdir / "meeting.yaml"
    meeting_yaml.write_text(
        _render_meeting_yaml(project, ledger, date, since, until, kind, artifacts, version),
        encoding="utf-8",
    )

    return BuildResult(
        bundle_dir=bdir, meeting_yaml=meeting_yaml, prep=prep_path,
        synthesis=synth_path, deck=deck_result, artifacts=artifacts, ledger=ledger,
    )


def _render_meeting_yaml(
    project: Project, ledger: WorkLedger, date: str, since: str, until: str,
    kind: str, artifacts: list, version: str,
) -> str:
    L: list = []
    a = L.append
    a(f"contract_version: {project.contract_version()}")
    a(f"project: {project.id}")
    a(f"pi: {project.pi}")
    a(f"date: {date}")
    a(f"kind: {kind}")
    a("status: prepped")
    a("window:")
    a(f"  since: {since}")
    a(f"  until: {until}")
    a(f"generated_by: project-update@{version}")
    a(f"source_head: {ledger.head_sha[:10]}")
    if artifacts:
        a("artifacts:")
        for art in artifacts:
            a(f"  - {Path(art).name}")
    else:
        a("artifacts: []")
    a("writeback:")
    a("  applied: false")
    a("  commit: null")
    a("  rows: []")
    return "\n".join(L) + "\n"


def _render_prep(
    project: Project,
    ledger: WorkLedger,
    deck: DeckResult,
    artifacts: list,
    meeting_date: str,
    synth_path: Path,
) -> str:
    L: list = []
    a = L.append
    a(f"# PI 1:1 prep — {meeting_date}")
    a("")
    a(f"**Project:** {project.name} · **With:** {project.pi}")
    a(f"**Window aggregated:** {ledger.since} → {ledger.until or 'now'} · "
      "**Generated by:** project-update (Tier-1)")
    a("")
    a("> All paths absolute. The `artifacts/` dir next to this file holds symlinks "
      "that always resolve to the current regenerated artifact (deck/PDF), even if "
      "a rebuild runs before the meeting.")
    a("")

    a("## 1 · What to open before the call")
    a("")
    if artifacts:
        for i, art in enumerate(artifacts, 1):
            real = Path(art).resolve()
            a(f"{i}. `{real}`  — symlink at `{art}`")
    else:
        a("_No built artifacts symlinked. Deck status:_ " + deck.message)
    a("")
    a(f"Full reconciliation + drift check: `{synth_path}`")
    a("")

    sf = ledger.scientific_focus or {}
    sci_lead = sf.get("first_sentence", "")
    sci_number = sf.get("top_headline_number", "")
    latest_news = _latest_news(ledger)

    a("## 2 · The 90-second opening")
    a("")
    substance = rank_commits_for_headline(ledger.commits)[:3]
    if latest_news:
        opening = f"This week: {latest_news}."
        if sci_lead:
            opening += f" Scientific frame: {sci_lead}"
        if sci_number:
            opening += f" {sci_number}."
        a(f"> \"{opening} "
          "A few engineering items were closed autonomously this window (FYI).\"")
    elif sci_lead:
        opening = sci_lead
        if sci_number:
            opening += f" Headline number: {sci_number}."
        a(f"> \"{opening} "
          "A few engineering items were closed autonomously this window (FYI).\"")
    elif substance:
        bullets = "; ".join(f"({i+1}) {c['subject']}" for i, c in enumerate(substance))
        a(f"> \"Since last meeting: {bullets}. "
          "One thing to discuss, a couple engineering items closed autonomously (FYI).\"")
    else:
        a("> \"Mostly documentation + reconciliation this window; let me walk the current state.\"")
    a("")

    a("## 3 · Headline (data, not advocacy)")
    a("")
    a("Lead with this window's actual news, then anchor to the project's own "
      "scientific framing + a canonical number — not a raw commit subject:")
    a("")
    if latest_news:
        a(f"- **This week:** {latest_news}")
        if sci_lead:
            a(f"    - scientific frame: {sci_lead}")
        if sci_number:
            a(f"    - data: {sci_number}")
    elif sci_lead:
        a(f"- **{sci_lead}**")
        if sci_number:
            a(f"    - data: {sci_number}")
    elif substance:
        a(f"- **{substance[0]['subject']}** (`{substance[0]['sha']}`)")
    a("")
    a("Show it; note the result; defer interpretation. Don't oversell.")
    a("")

    a("## 4 · Walk-through")
    a("")
    deck_src = project.deck.get("source")
    if deck.built and deck.output:
        a(f"Open the regenerated deck (`{deck.output}`) and walk slides in order. "
          "Captions are embedded — no separate notes needed.")
    elif deck_src:
        a(f"Deck source: `{project.repo / deck_src}` "
          f"(regenerate with `{deck.command or project.deck.get('builder')}`).")
        a("")
        a("Deck build status: " + deck.message)
    else:
        a("No deck registered for this project — walk the synthesis sections instead.")
    a("")

    a("## 5 · Decisions to extract")
    a("")
    a("> **Framing rule:** engineering/infra decisions are autonomous — do NOT "
      "escalate. The PI's time is for scientific direction + policy they drive.")
    a("")
    if ledger.pi_flagged_asks or ledger.open_decisions:
        a("### Ask PI (open PI-decision queue, pulled forward)")
        a("")
        if ledger.pi_flagged_asks:
            a("**🔴 PI-flagged workstream asks (raise these FIRST — blocking, "
              "escalated for the PI):**")
            a("")
            for ask in ledger.pi_flagged_asks:
                line = f"- **{ask['workstream']}** {ask['directive']}"
                if ask.get("recommendation"):
                    line += f" — _{ask['recommendation']}_"
                a(line)
            a("")
        if ledger.open_decisions:
            a("**Decision-queue items (D.N):**")
            a("")
            for d in ledger.open_decisions[:10]:
                a(f"- {_clean_row(d)}")
            a("")
    else:
        a("_No open PI-decision-queue rows detected in the project TRACKER._")
        a("")
    eng = [c for c in ledger.commits if (c["prefix"] or "") in {"compute", "chore", "refactor"}]
    if eng:
        a("### Closed autonomously (FYI only — do not re-litigate)")
        a("")
        for c in eng[:6]:
            a(f"- `{c['sha']}` {c['subject']}")
        a("")

    a("## 6 · Drift flags (verify before the meeting)")
    a("")
    if ledger.claimed_not_evidenced:
        a(f"{len(ledger.claimed_not_evidenced)} claimed items lack code/file evidence "
          "— most are legitimately doc-only (e.g. an emailed approval). Skim them in "
          f"`{synth_path}` before claiming them as done to the PI.")
    else:
        a("None — claimed and real are in sync this window.")
    a("")

    a("---")
    a("## 7 · Post-meeting")
    a("")
    a("After the meeting, paste the raw transcript into `TRANSCRIPT.md` next to "
      "this file (the canonical home). LabSync (Tier 2) then reads this bundle, "
      "extracts directives, and writes them back into the project TRACKER — the "
      "engine never does that itself.")
    a("")
    return "\n".join(L) + "\n"


def _latest_news(ledger: WorkLedger) -> str:
    """The most-recent in-window CHANGELOG development as a terse one-liner
    (`<date>: <heading>`). Empty if no in-window CHANGELOG entries."""
    entries = ledger.changelog_entries
    if not entries:
        return ""
    e = entries[0]  # newest-first as written in the CHANGELOG
    head = e.get("heading") or "(update)"
    return f"{e['date']}: {head}"


def _clean_row(text: str) -> str:
    t = text.strip()
    if t.startswith("|"):
        cells = [c.strip() for c in t.strip("|").split("|") if c.strip()]
        return " · ".join(cells[:4])
    return t
